### ISSUE TITLE
data titles

### ISSUE THREAD

**Issue by javadfarah** [cinemagoer/cinemagoer#383]
hi everyone !
this is not issue
please some one tell me what is this title meanings?
s_soundex and sn_soundex in name_basics
t_soundex in title akas
t_soundex in title basics

thanks

**Comment by alberanid** [comment]
hi @javadfarah , they are soundex versions of the title for movies and first name, surname, surname + first name for persons.

They are used doing a search.

A soundex algorithm takes a string and produce a representation of how it's pronounced (in this case, in English) so that it's possible to find a title even if we do not find any exact match.

For more details: https://en.wikipedia.org/wiki/Soundex
