### ISSUE TITLE
Trying to translate titles

### ISSUE THREAD

**Issue by Chris230291** [cinemagoer/cinemagoer#390]
I am trying to translate titles.

```
from imdb import Cinemagoer, helpers

programmeTitle = 'Supercoches a medida'
ia = Cinemagoer()
programmes = ia.search_movie(programmeTitle)
if programmes:
    programme = programmes[0]
    programmeTitle = programme['title']
    print(programmeTitle)
    ia.update(programme)
    print(helpers.getAKAsInLanguage(programme, 'es-ES'))
    print(programme["akas"])
else:
    print("Not found")
```
Outputs:
```
Supercar Megabuild
[]
['Supercoches a medida (Spain)', 'Criadores de Supercarros (Brazil)', 'Supercar - Macchine da sogno (Italy)']
```

There are a couple of things I am unsure about here.
Firstly I cant get the akas language helper to work.
Secondly is it possible to return `None` if that language doesn't exist?

Thanks,
Chris

EDIT: Also I noticed that the akas list doesn't container the original language (English)

**Comment by Chris230291** [comment]
I think the empty list might be because the languages are not being detected?

```
print(helpers.akasLanguages(programme))

[(None, 'Supercoches a medida (Spain)'), (None, 'Criadores de Supercarros (Brazil)'), (None, 'Supercar - Macchine da sogno (Italy)')]
```

Does anyone know why they are all `None` despite having the country names in brackets?

**Comment by alberanid** [comment]
hi @Chris230291 , pardon the long delay: it's surely a bug.

The `akaLanguages` expects a string like 'title::country', while currently we have 'title (country)'.

Things to do:
* [ ] verify that for titles that have the same translations in two countries, two separated entries are created (and not, for example, something like "Title (Portugal, Brazil)")
* [ ] verify that the "akas from release info" key contains data in the same format
* [ ] rethink the whole `akasLanguages` function and maybe other: for sure it doesn't return a list of `(lang, AKA)` tuples, since it would be `(country, AKA)`
* [ ] fix the bug / improve the current situation

**Comment by Chris230291** [comment]
Thanks for looking in to it.
What I am trying to do is feed the function a title and a language to translate to, then it return the translated title in the given language or None if it doesn't exist.
