### ISSUE TITLE
Limited movies returned for actors

### ISSUE THREAD

**Issue by clearcutgit** [cinemagoer/cinemagoer#424]
This is noted on the website changelog:
"Please notice that since now, the person pages will return a very limited list of movies for each role."

Is this intentional or a limitation?
If intentional is there a way to return all of their movies?

Thanks

**Comment by alberanid** [comment]
It's due to the fact that after the recent redesign pages about persons contain very few items about their careers until you "load more" via JavaScript.

See the HTML of https://imdb.com/name/nm0000148/ as an example.

If someone knows of a page that contains all the information related to a person without the need to dynamically load them, we can write a parser for it.

I do not think it would be easy (or worth the time and hassle) to try to behave like a browser and emulate the JavaScript calls.

**Comment by uyar** [comment]
I think this is it:

https://www.imdb.com/name/nm0005251/fullcredits/

**Comment by alberanid** [comment]
@uyar : yes, that's for sure our best option!

Right now for imdb.Person we retrieve 'main', 'filmography', 'biography' information, with 'main' and 'filmography' being the same page.

We could probably introduce a separated parser for `get_person_filmography` and remove it from `get_person_main`.

I'm not sure how complex it would be to parse that page, but it doesn't look too hard.
